name: Code Review with GPT

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - dev
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: read

jobs:
  check-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check Trigger from PR or Comment
        id: check_trigger
        env:
          PR_TITLE: "${{ github.event.pull_request.title }}"
          PR_BODY: "${{ github.event.pull_request.body }}"
          COMMENT_BODY: "${{ github.event.comment.body }}"
          EVENT_NAME: "${{ github.event_name }}"
        run: |
          echo "Checking PR or Comment for trigger '@GPT'..."
          TRIGGER_FOUND=false

          if [ "$EVENT_NAME" == "pull_request" ]; then
            if echo "$PR_BODY" | grep -iq "@GPT"; then
              TRIGGER_FOUND=true
            fi
          elif [ "$EVENT_NAME" == "issue_comment" ]; then
            if echo "$COMMENT_BODY" | grep -iq "@GPT"; then
              TRIGGER_FOUND=true
            fi
          fi

          echo "Trigger found: $TRIGGER_FOUND"
          echo "trigger_found=$TRIGGER_FOUND" >> $GITHUB_ENV

  review:
    needs: check-trigger
    runs-on: ubuntu-latest
    if: env.trigger_found == 'true'
    steps:
      - name: Run GPT Code Review
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Korean

      - name: Skip Job if Trigger Not Found
        run: |
          echo "⚠️ Trigger not found. Skipping the job."
