name: Docs

on:
  push:
    branches:
      - action


jobs:
  notebooks:
    name: "Build the notebooks for the docs"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry and Packages
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install

      - name: Build HTML
        uses: ammaraskar/sphinx-action@master

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: html-docs
          path: docs/build/html/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.PAT_GITHUB }}
          publish_dir: docs/build/html

#      - name: Trigger RTDs build
#        uses: dfm/rtds-action@v1
#        with:
#          webhook_url: ${{ secrets.RTD_WEBHOOK_URL }}
#          webhook_token: ${{ secrets.RTD_TOKEN }}
#          commit_ref: ${{ github.ref }}