name: Deploy Documentation

on:
  push:
    branches:
      - main
      - dev
      - chore
      - doc
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - dev
      - chore

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install poetry
        run: |
          python3 -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"
          poetry --version

      - name: Install project dependencies
        run: |
          poetry install --no-root

      - name: Install Sphinx and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-sphinx
          pip install sphinx sphinx-rtd-theme sphinx-intl

      - name: Generate API documentation
        run: |
          poetry run sphinx-apidoc -o docs/source/ ./zae_engine

      - name: Extract translations
        run: |
          cd docs
          poetry run sphinx-build -b gettext source locale

      - name: Update translations
        run: |
          cd docs
          poetry run sphinx-intl update -p locale -l ko

      - name: Build English documentation
        env:
          GA_MEASUREMENT_ID: ${{ secrets.GA_MEASUREMENT_ID }}
        run: |
          cd docs
          poetry run make clean
          poetry run make -e SPHINXOPTS="-D language=en" html
          mkdir -p build/lang/en
          mv build/html/* build/lang/en/
          echo "English build directory:"
          ls -R build/lang/en

      - name: Build Korean documentation
        env:
          GA_MEASUREMENT_ID: ${{ secrets.GA_MEASUREMENT_ID }}
        run: |
          cd docs
          poetry run make clean
          poetry run make -e SPHINXOPTS="-D language=ko" html
          mkdir -p build/lang/ko
          cp -r build/html/* build/lang/ko/
          echo "Korean build directory:"
          ls -R build/lang/ko

      - name: Create auto redirect index.html
        run: |
          mkdir -p build/lang
          echo '<!DOCTYPE html><html><head><title>Redirecting...</title><script>const userLang = navigator.language || navigator.userLanguage;if (userLang.startsWith("ko")) {window.location.href = "./ko/";} else {window.location.href = "./en/";}</script><noscript><p>Your browser does not support JavaScript. Please select your language:</p><ul><li><a href="./en/">English</a></li><li><a href="./ko/">한국어</a></li></ul></noscript></head><body><p>Redirecting based on your browser language...</p></body></html>' > docs/build/lang/index.html
          echo "Redirect file created in docs/build/lang/index.html"
          ls build/lang

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_GITHUB }}
          publish_branch: docs
          publish_dir: docs/build/lang
          force_orphan: true
