name: Deploy Documentation

on:
  push:
    branches:
      - main
      - dev
      - chore
      - documentation
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - dev
      - chore

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 전체 커밋 이력 가져오기

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install poetry
        run: |
          python3 -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"
          poetry --version

      - name: Install project dependencies
        run: |
          poetry install --no-root

      - name: Install Sphinx on Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-sphinx
          pip install sphinx sphinx-rtd-theme

      - name: Build documentation
        env:
          GA_MEASUREMENT_ID: ${{ secrets.GA_MEASUREMENT_ID }}
        run: |
          poetry run sphinx-apidoc -o docs/source/ ./zae_engine
          cd docs
          make clean
          poetry run make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_GITHUB }}
          publish_branch: docs
          publish_dir: docs/build/html
          force_orphan: true  # docs 브랜치를 강제로 덮어쓰기
