# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: W&B login test

on:
  push:

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}
    
    
    strategy:
      matrix:
        python-version: ["3.10"]
        os: ["ubuntu-latest"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }} at ${{ matrix.os }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Login W&B
      shell: bash
      env:
        WANDB_API: ${{ secrets.WANDB_KEY }}
      run: |
        pip install wandb
        chmod +x $(which wandb)
        wandb login "$WANDB_API"

